[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[test]
startup_wait = 10000

[test.validator]
bind_address = "127.0.0.1"
rpc_port = 18999
faucet_port = 19900

[programs.devnet]
spotr_markets = "4L3ARpxux9pP3hAMKsmGt325CkELLjnXq7S98eQpJaB4"

[programs.localnet]
spotr_markets = "4L3ARpxux9pP3hAMKsmGt325CkELLjnXq7S98eQpJaB4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
